import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mastery Link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" href="apple-touch-icon.html" />
        <link rel="icon" href="/images/favicon.png" type="image/x-icon" />
        <link rel="stylesheet" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/css/feather.css" />
        <link rel="stylesheet" href="/css/fontawesome/fontawesome.css" />
        <link rel="stylesheet" href="/css/select2.min.css" />
        <link rel="stylesheet" href="/css/splide.min.css" />
        <link rel="stylesheet" href="/css/main.css" />
      </head>
      <body className={inter.className}>{children}</body>

      <Script src="/js/vendor/jquery.min.js" />
      <Script src="/js/vendor/popper-core.js" />
      <Script src="/js/vendor/bootstrap.min.js" />
      <Script src="/js/vendor/appear.js" />
      <Script src="/js/vendor/countTo.js" />
      <Script src="/js/vendor/splide.min.js" />
      <Script src="/js/vendor/select2.min.js" />
      <Script src="/js/vendor/tippy.js" />
      <Script src="/js/vendor/typed.min.js" />
      <Script src="/js/main.js" />
    </html>
  );
}
